[book]
title = "Rust for Linux"
author = "Rust for Linux Contributors"
description = "Adding support for the Rust language to the Linux kernel"
language = "en"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/Rust-for-Linux/rust-for-linux.com"
edit-url-template = ""
no-section-label = true

[output.html.redirect]
# Do not provide a `/pinned-init` redirect here, since we do not want a file
# without an extension (e.g. Netlify takes care of serving the `/pinned-init`
# path from the file automatically, like for the rest of the files, and having
# a file there would be served by default as `text/plain` which would not work).
"/pinned-init.html" = "/pin-init"

[output.html.fold]
enable = true
level = 0
